name: Deploy to TransIP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH manually
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TRANSIP_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H trengi.ssh.transip.me >> ~/.ssh/known_hosts

      - name: Debug SSH Connection
        run: ssh -vvv trendify-dubaicom@trengi.ssh.transip.me echo "SSH connection works!"

      - name: Deploy files via rsync
        run: |
          set -x
          rsync -avz --delete \
            --exclude='.git/' \
            --exclude='node_modules/' \
            ./ trendify-dubaicom@trengi.ssh.transip.me:~/www/
